- hosts: localhost
  tasks:
  - name: Creating an empty file
    file:
      path: "/Users/Harry.Marvell/Desktop/HWC/.env"
      state: touch
      
  - name: Creating Environment Variable
    copy:
      dest: "/Users/Harry.Marvell/Desktop/HWC/.env"
      content: TASK="Hello World!"
