- hosts: localhost
  tasks:
  - name: Creating an empty file
    file:
      path: "/Users/<user>/Desktop/HWC/.env"
      state: touch
      
  - name: Creating Environment Variable
    copy:
      dest: "/Users/<user>/Desktop/HWC/.env"
      content: TASK="Hello World!"
